# fly.toml app configuration file generated for phonebook-backend-spring24 on 2024-04-26T14:12:22+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phonebook-backend-spring24'
primary_region = 'hkg'

[build]

[build.services]
    [build.services.backend]
      handler = "node"
      # Set the path to your index.js file
      command = "node index.js"

[env]
PORT = "3001" # add this


[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
