# fly.toml app configuration file generated for phonebook-backend1 on 2024-01-22T20:16:40+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "phonebook-backend1"
primary_region = "arn"

[build]

 [build.services]
    [build.services.backend]
      handler = "node"
      # Set the path to your index.js file
      command = "node index.js"

[env]
PORT = "3001" # add this


[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
